export enum EnumSecciones {
  ADMINISTRACIONES = 'Administraciones',
  ASIGNATURAS = 'Asignaturas',
  ASISTENCIAS = 'Asistencias',
  BIBLIOTECAS = 'Bibliotecas',
  CALENDARIO = 'Calendario',
  COMUNICACIONES = 'Comunicaciones',
  CURSOS = 'Cursos',
  ESTUDIANTES = 'Estudiantes',
  ESCUELAS = 'Escuelas',
  EVENTOS = 'Eventos',
  FINANZAS = 'Finanzas',
  NOTIFICACIONES = 'Notificaciones',
  PROFESORES = 'Profesores',
  REPORTES = 'Reportes',
  ROLES = 'Roles',
  TUTORES = 'Tutores',
  USUARIOS = 'Usuarios',
  VISITANTES = 'Visitantes',
  AUTH = 'Auth',
}
