export enum EnumSecciones {
  ADMINISTRACIONES = 'Administraciones',
  ASIGNATURAS = 'Asignaturas',
  CALIFICACIONES = 'Calificaciones',
  GRUPOS = 'Grupos',
  ASISTENCIAS = 'Asistencias',
  BIBLIOTECAS = 'Bibliotecas',
  CALENDARIO = 'Calendarios',
  COMUNICACIONES = 'Comunicaciones',
  CURSOS = 'Cursos',
  ESTUDIANTES = 'Estudiantes',
  ESCUELAS = 'Escuelas',
  EVENTOS = 'Eventos',
  FINANZAS = 'Finanzas',
  NOTIFICACIONES = 'Notificaciones',
  PROFESORES = 'Profesores',
  REPORTES = 'Reportes',
  ROLES = 'Roles',
  TUTORES = 'Tutores',
  USUARIOS = 'Usuarios',
  VISITANTES = 'Visitantes',
  AUTH = 'Auth',
  MENUS = 'Menus',
}

export enum EnumSeccion {
  ADMINISTRACION = 'Administracion',
  ASIGNATURA = 'Asignatura',
  CALIFICACION = 'Calificacion',
  GRUPO = 'Grupo',
  ASISTENCIA = 'Asistencia',
  BIBLIOTECA = 'Biblioteca',
  CALENDARIO = 'Calendario',
  COMUNICACION = 'Comunicacion',
  CURSO = 'Curso',
  ESTUDIANTE = 'Estudiante',
  ESCUELA = 'Escuela',
  EVENTO = 'Evento',
  FINANZA = 'Finanza',
  NOTIFICACION = 'Notificacion',
  PROFESOR = 'Profesor',
  REPORTE = 'Reporte',
  ROL = 'Rol',
  TUTOR = 'Tutor',
  USUARI = 'Usuario',
  VISITANTE = 'Visitante',
  MENU = 'Menu',
}
